#!/bin/bash
#
#$ -cwd
#
#$ -P tokp
#
#$ -j y
#
#$ -l h_rt=5:00:00
#
#$ -pe impi_hydra 32
#
#$ -m bea
#$ -M omaj@ipp.mpg.de
#
#$ -notify
#
#$ -N Focus
#
# change directory to where the code is found
cd /tokp/work/omaj/WKBEAM

# load modules
module load intel
module load mkl
module load gcc
module load hdf5-serial
module load impi
module load py33-python
module load py33-configobj
module load py33-numpy     
module load py33-scipy
module load py33-cython
module load py33-dateutil
module load py33-h5py
module load py33-mpi4py

# run the code
mpirun -np 32 python WKBeam.py trace StandardCases/Focus/Focus_raytracing.txt

exit 0
