#!/bin/bash
#
#$ -cwd
#
#$ -P tokp
#
#$ -j y
#
#$ -l h_rt=2:00:00
#
#$ -pe impi_hydra 32
#
#$ -m bea
#$ -M omaj@ipp.mpg.de
#
#$ -notify
#
#$ -N ITERtest
#
# change directory to where the code is found
cd /tokp/work/omaj/WKBEAM

# load modules
module load intel
module load mkl
module load gcc
module load hdf5-serial
module load impi
module load py27-python
module load py27-configobj
module load py27-numpy     
module load py27-scipy
module load py27-cython
module load py27-dateutil
module load py27-h5py
module load py27-mpi4py

# run the code
mpirun -np 32 python WKBeam.py trace StandardCases/AUG30907_0_72/AUG0fluct_raytracing.txt

exit 0
